language: scala
scala:
   - 2.12.7
jdk:
  - oraclejdk8
before_script:
  # pull down gwen source dependency
  - cd ..
  - git clone https://github.com/gwen-interpreter/gwen.git
  - cd gwen-web
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
sudo: required
addons:
  chrome: stable
before_install:
  - wget https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
  - mkdir chromedriver
  - unzip -o chromedriver_linux64.zip -d chromedriver
  - export PATH=$PATH:$PWD/chromedriver
sbt_args: -Dgwen.web.browser=chrome -Dgwen.web.browser.headless=true